const TEXT={zh:{title:'放学后 · 校园解谜',brand:'放学后',goalLabel:'当前目标',itemsLabel:'随身物品',empty:'空空如也',name:'林小满',avatar:'林',start:'我的手机没电了……先在教室里找找看吧。',rooms:['教室','走廊','配电室'],goals:['找到能照亮走廊的东西','为手电筒找到电池','寻找配电室密码','让三盏灯重新亮起','谜题完成'],scenes:{classroom:['第一章 · 无人的教室','暮色教室','放学铃已经响了很久。门外一片漆黑，广播却忽然传出一句话：<br>“想离开学校，就让三盏灯重新亮起。”'],hallway:['第二章 · 沉默的走廊','旧校舍走廊','手电筒划开黑暗。墙上的校史照片缺了一角，尽头的配电室门紧闭着。'],power:['第三章 · 最后一盏灯','配电控制室','空气里有淡淡的灰尘味。控制台上三枚开关旁，写着“过去、现在、未来”。']},spots:{desk:'翻找课桌',board:'查看黑板',locker:'检查储物柜',photo:'校史照片',door:'配电室门',window:'窗边纸条',panel:'控制台',cabinet:'工具柜'},items:{flashlight:'🔦 手电筒',battery:'🔋 电池',photo:'🖼️ 照片碎片',key:'🗝️ 铜钥匙'}},en:{title:'After School · A Campus Mystery',brand:'After School',goalLabel:'CURRENT OBJECTIVE',itemsLabel:'INVENTORY',empty:'Nothing yet',name:'Lin Xiaoman',avatar:'L',start:'My phone is dead... I should search the classroom first.',rooms:['Classroom','Hallway','Power Room'],goals:['Find something to light the hallway','Find a battery for the flashlight','Find the code to the power room','Turn the three lights back on','Mystery solved'],scenes:{classroom:['CHAPTER 1 · THE EMPTY CLASSROOM','Classroom at Dusk','The final bell rang long ago. The hallway is pitch-black, but the intercom suddenly whispers:<br>“To leave the school, bring the three lights back to life.”'],hallway:['CHAPTER 2 · THE SILENT HALLWAY','The Old Hallway','The flashlight cuts through the darkness. A piece is missing from the school photo, and the power-room door is locked.'],power:['CHAPTER 3 · THE LAST LIGHT','Power Control Room','Dust hangs in the air. Three switches on the control panel read “Past, Present, Future.”']},spots:{desk:'Search desk',board:'Read blackboard',locker:'Check locker',photo:'School photo',door:'Power-room door',window:'Window note',panel:'Control panel',cabinet:'Tool cabinet'},items:{flashlight:'🔦 Flashlight',battery:'🔋 Battery',photo:'🖼️ Photo piece',key:'🗝️ Brass key'}}};
const positions={classroom:[['desk',31,61],['board',72,39],['locker',84,63]],hallway:[['photo',28,49],['door',79,57],['window',52,69]],power:[['panel',62,54],['cabinet',28,64]]};
const state={lang:'zh',room:'classroom',items:new Set,done:new Set,unlocked:false,finished:false,message:'start',speaker:'hero',music:false,voice:true},$=s=>document.querySelector(s),modal=$('#modal');
let audioCtx,musicTimer,musicStep=0;
function tr(zh,en){return state.lang==='zh'?zh:en}
function speak(text){if(!state.voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/<[^>]+>/g,' '));u.lang=state.lang==='zh'?'zh-CN':'en-US';u.rate=state.lang==='zh'?.92:.9;u.pitch=1.08;const voices=speechSynthesis.getVoices(),match=voices.find(v=>v.lang.toLowerCase().startsWith(state.lang==='zh'?'zh':'en'));if(match)u.voice=match;speechSynthesis.speak(u)}
function say(zh,en,speaker='hero'){state.message=state.lang==='zh'?zh:en;state.speaker=speaker;$('#speaker').textContent=speaker==='radio'?tr('广播','Intercom'):TEXT[state.lang].name;$('#message').textContent=state.message;speak(state.message)}
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
function tone(freq,duration=.16,type='sine',volume=.045,delay=0){ensureAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(.001,now);g.gain.exponentialRampToValueAtTime(volume,now+.02);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g).connect(audioCtx.destination);o.start(now);o.stop(now+duration+.03)}
function sfx(kind){if(kind==='click')tone(520,.08,'sine',.025);if(kind==='item'){tone(659,.2,'sine',.05);tone(880,.28,'sine',.04,.12)}if(kind==='wrong'){tone(180,.22,'sawtooth',.025);tone(140,.25,'sawtooth',.02,.15)}if(kind==='unlock'){[392,523,659].forEach((n,i)=>tone(n,.25,'triangle',.04,i*.12))}if(kind==='win'){[523,659,784,1047].forEach((n,i)=>tone(n,.45,'sine',.05,i*.16))}}
function react(mood='curious',emoji='🔍'){const c=$('#character');c.className='character';void c.offsetWidth;c.className=`character ${mood}`;$('#emotion').textContent=emoji;if(mood==='happy'||mood==='celebrate'){const f=$('#sceneFlash');f.className='';void f.offsetWidth;f.className='flash'}if(mood!=='celebrate')setTimeout(()=>{c.className='character curious';$('#emotion').textContent='🔍'},1500)}
function musicNote(){if(!state.music)return;const notes=[220,261.63,329.63,293.66,196,246.94,329.63,261.63];tone(notes[musicStep++%notes.length],1.6,'sine',.012);if(musicStep%2===0)tone(notes[(musicStep+3)%notes.length]/2,2,'triangle',.008);musicTimer=setTimeout(musicNote,900)}
function toggleMusic(){state.music=!state.music;$('#music').classList.toggle('on',state.music);$('#music').classList.toggle('off',!state.music);$('#music').setAttribute('aria-pressed',state.music);if(state.music){ensureAudio();musicNote()}else clearTimeout(musicTimer)}
function toggleVoice(){state.voice=!state.voice;$('#voice').classList.toggle('on',state.voice);$('#voice').classList.toggle('off',!state.voice);$('#voice').setAttribute('aria-pressed',state.voice);if(!state.voice&&'speechSynthesis'in window)speechSynthesis.cancel();else speak(state.message==='start'?tr(TEXT.zh.start,TEXT.en.start):state.message)}
function addItem(id,zh,en){state.items.add(id);inventory();const newest=$(`.item-${id}`);if(newest)newest.classList.add('new');react('happy','✨');sfx('item');say(`获得了「${zh}」。`,`You found: ${en}.`)}
function inventory(){const t=TEXT[state.lang];$('#inventory').innerHTML=state.items.size?[...state.items].map(x=>`<span class="item item-${x}"><i></i><em>${t.items[x].replace(/^\S+\s/,'')}</em></span>`).join(''):t.empty}
function goal(){let n=0;if(state.items.has('flashlight'))n=1;if(state.items.has('battery'))n=2;if(state.unlocked)n=3;if(state.finished)n=4;$('#goal').textContent=TEXT[state.lang].goals[n]}
function render(){const t=TEXT[state.lang],r=t.scenes[state.room];document.documentElement.lang=state.lang==='zh'?'zh-CN':'en';document.title=t.title;$('#brand').textContent=t.brand;$('#goalLabel').textContent=t.goalLabel;$('#itemsLabel').textContent=t.itemsLabel;$('#avatar').textContent=t.avatar;$('#lang').textContent=state.lang==='zh'?'EN':'中文';$('#scene').className=state.room;$('#chapter').textContent=r[0];$('#title').textContent=r[1];$('#desc').innerHTML=r[2];$('#spots').innerHTML=positions[state.room].map(x=>`<button class="spot ${state.done.has(x[0])?'done':''}" data-id="${x[0]}" data-label="${t.spots[x[0]]}" style="left:${x[1]}%;top:${x[2]}%">${state.done.has(x[0])?'✓':'?'}</button>`).join('');document.querySelectorAll('.spot').forEach(b=>b.onclick=()=>act(b.dataset.id));document.querySelectorAll('nav button').forEach((b,i)=>{b.textContent=`0${i+1} ${t.rooms[i]}`;b.classList.toggle('active',b.dataset.room===state.room);b.classList.toggle('locked',b.dataset.room==='power'&&!state.unlocked)});inventory();goal()}
function pop(zhTitle,enTitle,zhBody,enBody,buttons=null,eye=null){$('#eyebrow').textContent=eye||tr('发现线索','CLUE FOUND');$('#modalTitle').textContent=tr(zhTitle,enTitle);$('#modalBody').innerHTML=tr(zhBody,enBody);$('#actions').innerHTML='';(buttons||[[tr('知道了','Got it'),close]]).forEach(([name,fn])=>{let b=document.createElement('button');b.className='action';b.textContent=name;b.onclick=fn;$('#actions').appendChild(b)});modal.showModal();speak(`${tr(zhTitle,enTitle)}。${tr(zhBody,enBody)}`)}function close(){modal.close();if('speechSynthesis'in window)speechSynthesis.cancel()}$('#close').onclick=close;
function act(id){react('curious','❓');sfx('click');if(id==='desk'){if(!state.items.has('flashlight')){addItem('flashlight','旧手电筒','an old flashlight');state.done.add(id);pop('一支旧手电筒','An Old Flashlight','<p>按下开关，没有反应——里面缺少电池。</p>','<p>You press the switch. Nothing—it needs a battery.</p>')}else say('桌洞已经翻过了。','I already searched this desk.')}
if(id==='locker'&&!state.items.has('battery')){addItem('battery','电池','a battery');state.done.add(id);pop('储物柜里的电池','A Battery in the Locker','<p>角落里正好有一节电池，手电筒亮了起来。</p>','<p>A battery is tucked in the corner. The flashlight flickers to life!</p>',[[tr('前往走廊','Go to hallway'),()=>{close();go('hallway')}]]);}
if(id==='board'){state.done.add(id);pop('黑板上的留言','Message on the Blackboard','<div class="note">三盏灯的顺序别弄错：<br>最老的先亮，今天的第二，明天的最后。</div>','<div class="note">Remember the order of the three lights:<br>The oldest first, today second, tomorrow last.</div>')}
if(id==='photo'){state.done.add(id);if(!state.items.has('photo'))addItem('photo','照片碎片','a photo piece');pop('1998 届毕业照','Class of 1998','<p>照片背面写着：“旧校舍启用：1998”。</p>','<p>The back says: “Old school building opened: 1998.”</p>')}
if(id==='window'){state.done.add(id);pop('窗边的留言','Note by the Window','<div class="note">门的密码，就是旧校舍启用的年份。</div>','<div class="note">The door code is the year the old building opened.</div>')}
if(id==='door'){if(!state.items.has('battery'))return say('走廊太黑，我什么也看不见。','It is too dark to see anything.');pop('门上的密码锁','Door Keypad','<p>输入旧校舍启用的年份：</p><input id="code" class="code" maxlength="4" inputmode="numeric" placeholder="____">','<p>Enter the year the old building opened:</p><input id="code" class="code" maxlength="4" inputmode="numeric" placeholder="____">',[[tr('解锁','Unlock'),code],[tr('再找找','Keep looking'),close]])}
if(id==='cabinet'&&!state.items.has('key')){addItem('key','铜钥匙','a brass key');state.done.add(id);pop('广播站备用钥匙','Spare Radio-Room Key','<p>它也许能解释是谁留下了谜题。</p>','<p>Maybe this will reveal who left the mystery behind.</p>')}if(id==='panel')panel();render()}
function code(){if($('#code').value==='1998'){state.unlocked=true;state.done.add('door');react('happy','🔓');sfx('unlock');close();go('power');say('密码正确，配电室的门开了！','Correct! The power-room door opens.')}else{react('startled','!');sfx('wrong');$('#code').value='';$('#code').placeholder=tr('密码不对','Wrong code')}}
function panel(){pop('三路电源开关','Three Power Switches','<p>按照黑板留言，依次点击正确的三盏灯。</p><div id="switches"></div>','<p>Use the blackboard clue and press the switches in order.</p><div id="switches"></div>',[],tr('最终谜题','FINAL PUZZLE'));let seq=[];[['future','未来','Future'],['past','过去','Past'],['present','现在','Present']].forEach(x=>{let b=document.createElement('button');b.className='action';b.textContent=tr(x[1],x[2]);b.onclick=()=>{seq.push(x[0]);b.disabled=true;if(seq.length===3)seq.join()==='past,present,future'?finish():(say('顺序不对，开关复位了。','Wrong order. The switches reset.','radio'),setTimeout(panel,300))};$('#switches').appendChild(b)})}
function finish(){state.finished=true;state.done.add('panel');react('celebrate','🎉');sfx('win');pop('灯亮了。','The Lights Are On.','<div class="ending"><b>💡</b><p>走廊、教室和校门的灯依次亮起。</p><p>“小满，欢迎加入校园探秘社。”</p><strong>你解开了旧校舍的秘密！</strong></div>','<div class="ending"><b>💡</b><p>The hallway, classroom, and school-gate lights come on.</p><p>“Xiaoman, welcome to the Campus Mystery Club.”</p><strong>You solved the secret of the old school!</strong></div>',[[tr('再玩一次','Play again'),reset]],tr('结局 · 灯火通明','ENDING · LIGHTS ON'));say('校门打开了。可那把广播站钥匙，似乎暗示着另一个故事……','The school gate opens. But that radio-room key hints at another mystery...');render()}
function go(r){if(r==='hallway'&&!state.items.has('battery')){react('startled','🌑');return say('外面太黑，得先让手电筒亮起来。','It is too dark. I need a working flashlight first.')}if(r==='power'&&!state.unlocked){react('startled','🔒');return say('配电室还锁着，需要找到密码。','The power room is locked. I need the code.')}state.room=r;render();const s=$('#scene');s.classList.add('scene-changing');setTimeout(()=>s.classList.remove('scene-changing'),800);react('curious','👀')}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.room));
function reset(){state.room='classroom';state.items.clear();state.done.clear();state.unlocked=false;state.finished=false;if(modal.open)close();render();say('我的手机没电了……先在教室里找找看吧。','My phone is dead... I should search the classroom first.')}$('#reset').onclick=()=>confirm(tr('确定重新开始吗？','Restart the game?'))&&reset();$('#lang').onclick=()=>{state.lang=state.lang==='zh'?'en':'zh';if(modal.open)close();render();say('已切换为中文，解谜进度已保留。','Language changed to English. Your progress is saved.')};$('#music').onclick=toggleMusic;$('#voice').onclick=toggleVoice;$('#music').classList.add('off');$('#voice').classList.add('on');document.addEventListener('pointerdown',()=>ensureAudio(),{once:true});render();
